@startuml Historia

State choice1 <<choice>>
State choice2 <<choice>>
State choice3 <<choice>>

IntroduccionHistoria -d-> PrimeraBifurcacion
PrimeraBifurcacion -d-> choice1
choice1 -l-> Respuesta1 : CaminoA
choice1 -r-> Respuesta2 : CaminoB

Respuesta1 -d-> SegundaBifurcacion
SegundaBifurcacion -d-> choice2

choice2 --> Respuesta1.1 : CaminoA
choice2 --> Respuesta1.2 : CaminoB

Respuesta2 -d-> TerceraBifurcacion
TerceraBifurcacion -d-> choice3

choice3 --> Respuesta2.1 : CaminoA
choice3 --> Respuesta2.2 : CaminoB

Respuesta1.1 -d-> FinalIncorrecto
Respuesta1.2 -d-> FinalIncorrecto
Respuesta2.1 -d-> FinalIncorrecto

Respuesta2.2 -d-> FinalCorrecto

@enduml